### ISSUE TITLE
Tests are broken on 0.3.6

### ISSUE THREAD

**Issue by ibash** [wdavidw/node-csv#192]
Hi there,

Running the tests on 0.3.6 fails with:
```
> csv@0.3.6 node-csv
> make test


node-csv/node_modules/coffee-script/lib/coffee-script/coffee-script.js:210
          throw new Error("Use CoffeeScript.register() or require the coffee-s
                ^
Error: Use CoffeeScript.register() or require the coffee-script/register module to require .coffee.md files.
  at Object._base.(anonymous function) [as .coffee] (node-csv/node_modules/coffee-script/lib/coffee-script/coffee-script.js:210:17)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at node-csv/node_modules/mocha/lib/mocha.js:185:27
  at Array.forEach (native)
  at Mocha.loadFiles (node-csv/node_modules/mocha/lib/mocha.js:182:14)
  at Mocha.run (node-csv/node_modules/mocha/lib/mocha.js:394:31)
  at Object.<anonymous> (node-csv/node_modules/mocha/bin/_mocha:394:16)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

This might be due to the package.json only specifiying "latest" instead of the actual versions it's compatible with.

Can you fix the package.json so I can run the tests / add one? Trying to find out whether a bug that is in 0.3.6 is also in 4. (whether we should upgrade or just fix the bug).

**Comment by wdavidw** [comment]
0.3.6 is no longer supported, you could replace the calls to `require "coffeescript"` with `require "coffee-script/register"`
