### ISSUE TITLE
csv() is not a function

### ISSUE THREAD

**Issue by ORESoftware** [wdavidw/node-csv#195]
I called

```npm install csv```

no problem

then I have this code

```javascript
var csv = require('csv');
var fs = require('fs');

csv().from.stream(fs.createReadStream('./csvfile.csv'))
    .transform( function(row){
        //row.unshift(row.pop());
        return row;
    })
    .on('record', function(row,index){
        console.log('#'+index+' '+JSON.stringify(row));
    })
    .on('end', function(count){
        console.log('Number of lines: '+count);
    })
    .on('error', function(error){
        console.log(error.message);
    });
```

and I get this error:

```javascript
csv().from.stream(fs.createReadStream('./csvfile.csv'))
^
TypeError: object is not a function
    at Object.<anonymous> (/Users/amills001c/WebstormProjects/redisCSVUploadProj/upload_csv.js:9:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

WTF? Please help thanks

**Comment by ORESoftware** [comment]
I just realized that this code is for the legacy version. Your legacy code looks a lot easier to use...

You should please provide the code read the stream from the CSV file in your newer examples. You omit the code that

does csv().from.stream

**Comment by wdavidw** [comment]
i might add sugar functions if I have time but at least the API is now 100% standart Node.js stream API

**Comment by ORESoftware** [comment]
cool no prob

**Comment by Lovebubu** [comment]
check fast-csv, const csv = require('fast-csv')

**Comment by kishan980** [comment]
how to store csv file mongoose database
